### ISSUE TITLE
Problem with PhP version 8.1.14

### ISSUE THREAD

**Issue by Vcarbon** [mbeurel/php-lemmatizer#1]
In PackageDiscoveryTrait.php line 312:

  Package mbeurel/php-lemmatizer has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - mbeurel/php-lemmatizer 0.1.3 requires php ^7.1 which does not match your installed version 8.1.14.

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by mbeurel** [comment]
I just released a new version compatible with PHP 8.*
