### ISSUE TITLE
TreeTagger not exist

### ISSUE THREAD

**Issue by Vcarbon** [mbeurel/php-lemmatizer#2]
Hello
When I install with composer, I get this error message

Fatal error: Uncaught Exception: The file "tree-tagger" not exist in /home/gmtk/www/treeTagger/bin/tree-tagger in /home/gmtk/vendor/mbeurel/php-lemmatizer/lib/TreeTagger.php:125 Stack trace: #0 /home/gmtk/vendor/mbeurel/php-lemmatizer/lib/TreeTagger.php(89): PhpTreeTagger\TreeTagger->verifyLibrary() #1 /home/gmtk/www/lemm.php(56): PhpTreeTagger\TreeTagger->__construct('french', Array) #2 {main} thrown in /home/gmtk/vendor/mbeurel/php-lemmatizer/lib/TreeTagger.php on line 125

**Comment by mbeurel** [comment]
Hello,

You must install the "TreeTagger" library -> https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/
After you define TreeTagger path with -> $treeTaggerPath = __DIR__."/treeTagger";

**Comment by Vcarbon** [comment]
That's OK.
