### ISSUE TITLE
treetagger gives good answers but the sample code gives an empty array.

### ISSUE THREAD

**Issue by Vcarbon** [mbeurel/php-lemmatizer#3]
the sample code , after adding $nbProcess = 6; gives an empty array.

**Comment by mbeurel** [comment]
Composer install with prod or dev ?
Can you give me the returns of the command ($debug = true)?

**Comment by Vcarbon** [comment]
I install with "composer require mbeurel/php-lemmatizer".

I used phplemmatizer programm on a URL , not a sh command.
The treeTagger command works well.

ssh1:~/www/treeTagger$ echo 'La lemmatisation désigne un traitement lexical apporté à un texte en vue de son analyse.' | cmd/tree-tagger-french
        reading parameters ...
        tagging ...
La      DET:ART le
lemmatisation   NOM     lemmatisation
désigne VER:pres        désigner
un      DET:ART un
traitement      NOM     traitement
lexical ADJ     lexical
apporté VER:pper        apporter
à       PRP     à
un      DET:ART un
texte   NOM     texte
en      PRP     en
vue     NOM     vue
de      PRP     de
son     DET:POS son
analyse NOM     analyse
.       SENT    .
         finished.
sh1:~/www/treeTagger$



Le lun. 20 févr. 2023 à 06:02, Matthieu Beurel ***@***.***> a
écrit :

**Comment by Vcarbon** [comment]
What does "Composer install **with** **prod** **or** **dev** ?" mean?

**Comment by Vcarbon** [comment]
Is there any solution to the issue?

**Comment by Vcarbon** [comment]
Without answer, I'm using another solution.
So don't care anymore.
